name: todo_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  another_flutter_splash_screen: ^1.2.0
  google_fonts: 6.1.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_messaging: ^14.7.19
  provider: ^6.1.1
  easy_date_timeline: ^1.0.3
  intl: ^0.19.0
  flutter_slidable: ^3.0.1
  shared_preferences: ^2.2.2
  animated_custom_dropdown: ^3.0.0
  firebase_crashlytics: ^3.4.18
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.8
  dots_indicator: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: "launcher_icon"

flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/images/


